# Custom types
types:
  # Structured response types
  SlideInfo:
    slot:
      type: number
      description: Slot number (1-indexed, permanent ID)
    headline:
      type: string
      description: The slide headline
    slideType:
      type: string
      description: Layout type (title, content, data, quote, section, conclusion)
      optional: true

  SlidefoxResponse:
    message:
      type: string
      description: Response message to the user (markdown supported)
    slides:
      type: array
      items:
        type: SlideInfo
      description: Current state of all slides in the deck, ordered by slot
    style:
      type: string
      description: The visual style being used
      optional: true

# Agent inputs
input:
  STYLE:
    type: string
    description: Visual style for the presentation
    optional: true
    default: auto

# Triggers
triggers:
  user-message:
    description: User describes their presentation
    input:
      USER_MESSAGE:
        type: string

# Agent configuration
agent:
  model: google/gemini-3-flash-preview
  system: system
  input:
    - STYLE
  imageModel: google/gemini-2.5-flash-image
  agentic: true
  maxSteps: 20

# Handlers
handlers:
  user-message:
    Add user message:
      block: add-message
      role: user
      prompt: user-message
      input:
        - USER_MESSAGE
      display: hidden

    Respond to user:
      block: next-message
      responseType: SlidefoxResponse
